# /// script
# requires-python = ">=3.12"
# dependencies = ["jsonschema", "pyyaml"]
# ///
"""Build and check the files of an idea partition sweep: corpus, prompts, reports and draft.

The partition-ideas skill runs every step of a sweep through this script, so no step depends on
a command typed out by hand. The subcommands, in the order a sweep uses them:

    idea_corpus.py locate                       # where the sweep's files live; exit 1 if unsafe
    idea_corpus.py start                        # resume a sweep, or move an earlier one aside
    idea_corpus.py build [--status open,triaged] [--seed N] [--exclude ids.txt] [--stats]
    idea_corpus.py prompt R1                    # one pack section, filled in, saved as sent
    idea_corpus.py report R1 --file reply.md    # write an agent's returned report, stamped
    idea_corpus.py name <corpus date>           # the draft's markdown and record paths
    idea_corpus.py check <draft.md> <draft.json>
    idea_corpus.py accept <draft.md> <draft.json>

**Where things live.** Subagents run in the primary checkout, whatever worktree the coordinator
is in, so every file an agent reads is in the primary checkout's staging directory
(``staging_dir``): the corpus, the reports and the synthesis draft. The primary checkout is the
first entry of ``git worktree list``. ``prompt`` fills each pack section with absolute paths
there, so the second audit reads the draft at a path it can open. The accepted partition is
copied by ``accept`` into ``partitions_dir`` in the current checkout, where it can be committed.

**The staging directory must be gitignored.** ``locate`` exits 1 when it is not, and every
subcommand that writes into it refuses to. ``locate`` also prints a digest of the primary
checkout's ``git status``; the skill compares it before and after its writes there.

**The corpus.** ``build`` selects the ideas whose folded status is in ``--status`` (one status or
a comma-separated list, default ``triaged``), minus the ids an optional ``--exclude`` file lists
(one six-digit id per line, ``#`` comments allowed; no file means no exclusions). It writes two
files that differ only in what they carry, so the control analyst cannot tell its input differs:

    corpus-R1.md   title, body, links, findings
    corpus-R4.md   title, body, links           <- the control

and ``manifest.json``: the corpus size, the status selection, the excluded ids, the ideas with
more than one finding, and a random seed that identifies the build. "Findings" are every
annotation of kind ``finding``, any author, in time order. ``--stats`` prints the manifest and
writes nothing.

**The run stamp.** Every file the sweep writes into the corpus directory, and the draft markdown,
starts with a stamp naming the build it belongs to. That is how ``start`` tells this sweep's
output from an earlier sweep's file at the same path.

Nothing here writes the idea log.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import random
import re
import shutil
import subprocess
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import paths
from ideas import INVERSE_LINK_TYPE, IdeaError, fold, legal_transitions, load_events
from jsonschema import Draft7Validator  # type: ignore[import-untyped]

PATH_KEYS = ("ideas_path", "ideas_view_path", "priority_path", "docs_root", "staging_dir",
             "partitions_dir")

#: The keys the ideas check reads, passed to it explicitly in the gate's check command.
CHECK_KEYS = ("ideas_path", "ideas_view_path", "priority_path")
PACK = paths.PLUGIN_ROOT / "docs" / "partition-pack.md"
SCHEMA = paths.PLUGIN_ROOT / "schemas" / "idea-partition-record.schema.json"
DEFAULT_STATUS = "triaged"
IDEA_ID = re.compile(r"^[0-9]{6}$")
PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")
SECTIONS = ("R1", "R4", "A1", "S", "A2", "G")

#: The file each dispatched section's returned report is written to.
REPORTS = {
    "R1": "report-R1.md",
    "R4": "report-R4.md",
    "A1": "audit-1-findings.md",
    "A2": "audit-2-findings.md",
}

#: The files ``start`` moves aside when a new sweep begins.
SWEEP_FILES = ("manifest.json", "corpus-*.md", "report-*.md", "audit-*.md", "dispatch-*.txt")

HEADER = """# Idea corpus — {analyst}

Generated by the partition sweep's corpus builder. Do not edit by hand.

{count} ideas, presented in id ascending order.{note}

---
"""

#: For the finding-reader only. The control's file never mentions findings, in an entry or in
#: the header: a control that can tell its input differs is not a control.
LAYERED_NOTE = """ Each entry carries its title, body, links and findings.

Ideas marked **LAYERED EVIDENCE** carry more than one finding. Treat those as layered and
possibly internally contradictory accounts rather than a single settled one."""

PLAIN_NOTE = " Each entry carries its title, body and links."


class CorpusError(Exception):
    """A sweep step that must not go on."""


# --- where things live ---------------------------------------------------------------------


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True,
                          check=False)


def primary_checkout(root: Path) -> Path:
    """The first entry of ``git worktree list``; the root itself outside a git repository."""
    listed = _git(root, "worktree", "list", "--porcelain")
    if listed.returncode == 0:
        for line in listed.stdout.splitlines():
            if line.startswith("worktree "):
                return Path(line.removeprefix("worktree ")).resolve()
    return root.resolve()


def _repository_of(path: Path) -> Path | None:
    """The top level of the git checkout holding ``path``, or None when there is none."""
    probe = path
    while not probe.exists() and probe != probe.parent:
        probe = probe.parent
    top = _git(probe if probe.is_dir() else probe.parent, "rev-parse", "--show-toplevel")
    return Path(top.stdout.strip()).resolve() if top.returncode == 0 else None


def is_ignored(directory: Path) -> bool:
    """Whether ``git check-ignore`` accepts files in ``directory``.

    A directory in no git checkout, or one git will not answer for, counts as not ignored:
    nothing but an accepted ``check-ignore`` lets the sweep write.
    """
    repository = _repository_of(directory)
    if repository is None:
        return False
    probe = directory.resolve() / "idea-partition-probe.md"
    return _git(repository, "check-ignore", "-q", str(probe)).returncode == 0


def guard_write(directory: Path) -> None:
    """Refuse to write into a checkout's directory that git does not ignore."""
    if not is_ignored(directory):
        raise CorpusError(f"{directory} is not gitignored in a git checkout. "
                          "Ignore it (the scaffold skill offers to) or configure a staging "
                          "directory that is.")


def status_digest(checkout: Path) -> str:
    """A short digest of ``git status --porcelain``, compared before and after a write."""
    listed = _git(checkout, "status", "--porcelain")
    return hashlib.sha256(listed.stdout.encode()).hexdigest()[:12]


@dataclass(frozen=True)
class Layout:
    root: Path          # the current checkout
    primary: Path       # the primary checkout, where subagents run
    staging: Path       # <primary>/<staging_dir>: drafts
    corpus: Path        # <staging>/corpus: corpus, dispatches and reports
    partitions: Path    # <root>/<partitions_dir>: accepted partitions
    idea_log: Path      # the log the corpus is read from, in the current checkout
    primary_idea_log: Path  # the same log in the primary checkout, as subagents see it
    systems: Path       # <primary>/<docs_root>/systems.yaml
    check_command: str  # the ideas check, with every path it reads spelled out


def layout(config: paths.Config) -> Layout:
    primary = primary_checkout(config.root)
    in_primary = paths.Config(primary, config.values)
    staging = in_primary.path("staging_dir")
    return Layout(
        root=config.root,
        primary=primary,
        staging=staging,
        corpus=staging / "corpus",
        partitions=config.path("partitions_dir"),
        idea_log=config.path("ideas_path"),
        primary_idea_log=in_primary.path("ideas_path"),
        systems=in_primary.path("docs_root") / "systems.yaml",
        check_command=" ".join(
            [f'uv run "{paths.PLUGIN_ROOT / "scripts" / "check.py"}" --feature ideas',
             f'--root "{config.root}"']
            + [f'{paths.KEYS[k].flag} "{config.path(k)}"' for k in CHECK_KEYS]),
    )


# --- the manifest and the run stamp --------------------------------------------------------


def read_manifest(corpus: Path) -> dict[str, Any] | None:
    manifest = corpus / "manifest.json"
    if not manifest.exists():
        return None
    data: dict[str, Any] = json.loads(manifest.read_text(encoding="utf-8"))
    return data


def corpus_date(corpus: Path) -> str:
    """The manifest's modification date, which the draft is named by."""
    stamp = (corpus / "manifest.json").stat().st_mtime
    return dt.date.fromtimestamp(stamp).isoformat()


def run_stamp(manifest: dict[str, Any]) -> str:
    return (f"<!-- partition-ideas: seed={manifest['shuffle_seed']} "
            f"corpus_size={manifest['corpus_size']} "
            f"status={','.join(manifest['status'])} -->")


def _stamped(path: Path, stamp: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8").startswith(stamp)


# --- the corpus ----------------------------------------------------------------------------


def valid_statuses() -> set[str]:
    """Every status the idea schema's transition table names."""
    transitions = legal_transitions()
    return {source for source, _ in transitions} | {target for _, target in transitions}


def parse_statuses(text: str) -> frozenset[str]:
    requested = [part.strip() for part in text.split(",") if part.strip()]
    if not requested:
        raise CorpusError("--status names no status")
    unknown = sorted(set(requested) - valid_statuses())
    if unknown:
        raise CorpusError(f"unrecognised status {', '.join(unknown)}; valid values are "
                          f"{', '.join(sorted(valid_statuses()))}")
    return frozenset(requested)


def load_exclusions(path: Path | None) -> set[str]:
    """Ids listed one per line; ``#`` starts a comment. No file means no exclusions."""
    if path is None:
        return set()
    if not path.exists():
        raise CorpusError(f"exclusion file {path} does not exist")
    ids = set()
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        value = line.split("#", 1)[0].strip()
        if not value:
            continue
        if not IDEA_ID.match(value):
            raise CorpusError(f"{path.name} line {number}: {value!r} is not a six-digit idea id")
        ids.add(value)
    return ids


def findings_of(entry: dict[str, Any]) -> list[dict[str, Any]]:
    """Every annotation of kind ``finding``, any author, in time order."""
    found = [a for a in entry.get("annotations") or [] if a.get("kind") == "finding"]
    return sorted(found, key=lambda a: str(a.get("at") or ""))


def select(state: dict[str, dict[str, Any]], statuses: frozenset[str],
           excluded: set[str]) -> tuple[dict[str, dict[str, Any]], dict[str, Any]]:
    """The corpus and the facts the manifest reports about it."""
    selected = {k: v for k, v in state.items() if v.get("status") in statuses}
    corpus = {k: v for k, v in selected.items() if k not in excluded}
    authors: dict[str, int] = {}
    for entry in corpus.values():
        for annotation in findings_of(entry):
            author = str(annotation.get("author"))
            authors[author] = authors.get(author, 0) + 1
    facts = {
        "ideas_in_log": len(state),
        "selected": len(selected),
        "excluded": sorted(excluded & set(selected)),
        "corpus_size": len(corpus),
        "status": sorted(statuses),
        "layered_evidence": sorted(k for k, v in corpus.items() if len(findings_of(v)) > 1),
        "ideas_without_findings": sorted(k for k, v in corpus.items() if not findings_of(v)),
        "finding_authors": dict(sorted(authors.items(), key=lambda kv: -kv[1])),
    }
    return corpus, facts


def _target(link: dict[str, Any]) -> str:
    return str(link.get("target") or link.get("target_code"))


def _inbound(corpus: dict[str, dict[str, Any]]) -> dict[str, list[tuple[str, str]]]:
    """Inbound edges per idea, so a dependency is visible from both ends."""
    inbound: dict[str, list[tuple[str, str]]] = {}
    for source, entry in corpus.items():
        for link in entry.get("links") or []:
            if link.get("retracted"):
                continue
            edge = INVERSE_LINK_TYPE.get(link["type"], link["type"])
            inbound.setdefault(_target(link), []).append((edge, source))
    return inbound


def render_idea(idea: str, entry: dict[str, Any], inbound: dict[str, list[tuple[str, str]]],
                *, include_findings: bool, layered: bool) -> str:
    """One idea's entry. The control's differs only in carrying no findings."""
    lines = [f"## {idea} — {entry.get('title', '')}"]
    if layered and include_findings:
        lines += ["", "**LAYERED EVIDENCE** — more than one finding."]
    lines += ["", str(entry.get("body") or "").strip()]
    edges = [f"- {link['type']} -> {_target(link)}"
             for link in entry.get("links") or [] if not link.get("retracted")]
    edges += [f"- {edge} <- {source}" for edge, source in sorted(inbound.get(idea, []))]
    if edges:
        lines += ["", "### Links", ""] + edges
    found = findings_of(entry) if include_findings else []
    if found:
        lines += ["", "### Findings", ""]
        for annotation in found:
            lines += [f"*{annotation.get('author')}, {annotation.get('at')}*", "",
                      str(annotation.get("text") or "").strip(), ""]
    return "\n".join(lines + ["", "---", ""]) + "\n"


def render(corpus: dict[str, dict[str, Any]], *, analyst: str, include_findings: bool,
           layered: set[str]) -> str:
    inbound = _inbound(corpus)
    head = HEADER.format(analyst=analyst, count=len(corpus),
                         note=LAYERED_NOTE if include_findings else PLAIN_NOTE)
    body = "".join(render_idea(idea, corpus[idea], inbound, include_findings=include_findings,
                               layered=idea in layered) for idea in sorted(corpus))
    return head + "\n" + body


def build(log: Path, out: Path, statuses: frozenset[str], exclude: Path | None = None,
          seed: int | None = None, stats: bool = False) -> dict[str, Any]:
    """Select and write the corpus; return the manifest. ``stats`` writes nothing."""
    corpus, facts = select(fold(load_events(log)), statuses, load_exclusions(exclude))
    if not corpus:
        raise CorpusError(f"no idea has status {', '.join(sorted(statuses))}; nothing to build")
    facts["exclusion_file"] = str(exclude) if exclude is not None else None
    facts["shuffle_seed"] = seed if seed is not None else random.randrange(2**31)
    facts["files"] = {"R1": "corpus-R1.md", "R4": "corpus-R4.md"}
    if stats:
        return facts
    guard_write(out)
    out.mkdir(parents=True, exist_ok=True)
    layered = set(facts["layered_evidence"])
    for analyst, include_findings in (("R1", True), ("R4", False)):
        text = render(corpus, analyst=analyst, include_findings=include_findings,
                      layered=layered)
        (out / facts["files"][analyst]).write_text(text, encoding="utf-8")
    (out / "manifest.json").write_text(json.dumps(facts, indent=2) + "\n", encoding="utf-8")
    return facts


# --- resume or start -----------------------------------------------------------------------


def _records(directories: Iterable[Path]) -> tuple[list[tuple[Path, dict[str, Any]]], list[str]]:
    """Every readable partition record in the directories, and a line per unreadable one."""
    found, unreadable = [], []
    for directory in directories:
        for path in sorted(directory.glob("idea-partition-*.json")):
            try:
                record = json.loads(path.read_text(encoding="utf-8"))
                record["manifest"]["shuffle_seed"]
            except (OSError, ValueError, TypeError, KeyError) as exc:
                unreadable.append(f"UNREADABLE (ignored): {path}: {type(exc).__name__}: {exc}")
                continue
            found.append((path, record))
    return found, unreadable


def start(where: Layout, today: str | None = None) -> list[str]:
    """Classify the invocation RESUME or NEW; on NEW, move the earlier sweep's files aside.

    A sweep counts as finished once a record carrying its seed is ``accepted``. Files are moved
    into ``previous-<modification date>/`` and never deleted or overwritten.
    """
    manifest = read_manifest(where.corpus)
    records, lines = _records([where.staging, where.partitions])
    if manifest is not None:
        stamp = run_stamp(manifest)
        done = [p.name for p in sorted(where.corpus.glob("*.md")) if _stamped(p, stamp)]
        ours = [(p, r.get("state")) for p, r in records
                if r["manifest"]["shuffle_seed"] == manifest["shuffle_seed"]]
        accepted = [p for p, state in ours if state == "accepted"]
        if done and not accepted:
            lines.append(f"RESUME: corpus built {corpus_date(where.corpus)}, size "
                         f"{manifest['corpus_size']}, seed {manifest['shuffle_seed']}")
            lines.append("already done: " + ", ".join(done))
            lines += [f"this sweep's record: {p} (state: {state})" for p, state in ours]
            return lines
        reason = f"accepted in {accepted[0]}" if accepted else "no stamped output"
        lines.append(f"NEW: the manifest in place ({reason}) belongs to an earlier sweep")
    else:
        lines.append("NEW: no manifest")
    if where.corpus.exists():
        guard_write(where.corpus)
    for pattern in SWEEP_FILES:
        for path in sorted(where.corpus.glob(pattern)):
            day = today or dt.date.fromtimestamp(path.stat().st_mtime).isoformat()
            target_dir = where.corpus / f"previous-{day}"
            target_dir.mkdir(exist_ok=True)
            target, n = target_dir / path.name, 2
            while target.exists():
                target, n = target_dir / f"{path.stem}-{n}{path.suffix}", n + 1
            path.rename(target)
            lines.append(f"moved {path.name} -> {target.relative_to(where.corpus)}")
    return lines


# --- the pack ------------------------------------------------------------------------------


def extract(pack: str, section: str) -> str:
    """The fenced block under ``### <section> ...``, exactly as written."""
    match = re.search(rf"^### {re.escape(section)} .*?^```\n(.*?)\n^```$", pack, re.S | re.M)
    if match is None:
        raise CorpusError(f"no fenced block found for section {section}")
    if re.search(r"^```", match.group(1), re.M):
        raise CorpusError(f"section {section} holds a nested fence; extraction would cut it")
    return match.group(1)


def fill(block: str, values: dict[str, str]) -> str:
    """Substitute every ``{placeholder}``; refuse to return a block with one left over."""
    missing = sorted({name for name in PLACEHOLDER.findall(block) if name not in values})
    if missing:
        raise CorpusError(f"no value for {', '.join('{' + m + '}' for m in missing)}")
    return PLACEHOLDER.sub(lambda m: values[m.group(1)], block)


def prompt_values(where: Layout, draft: Path | None) -> dict[str, str]:
    values = {
        "corpus_dir": str(where.corpus),
        "idea_log": str(where.primary_idea_log),
        "systems_registry": str(where.systems),
        "check_command": where.check_command,
    }
    if draft is not None:
        resolved = draft.resolve()
        if not resolved.is_relative_to(where.staging):
            raise CorpusError(f"the draft {resolved} is not in the primary checkout's staging "
                              f"directory {where.staging}, so a subagent cannot be sent to it")
        values["draft"] = str(resolved)
    return values


def prompt(where: Layout, section: str, draft: Path | None = None,
           pack: Path = PACK) -> str:
    """Extract and fill one section, and save exactly that text as ``dispatch-<section>.txt``."""
    if section not in SECTIONS:
        raise CorpusError(f"unknown section {section}; the pack's are {', '.join(SECTIONS)}")
    if section == "A2" and (draft is None or not draft.exists()):
        raise CorpusError("the second audit needs --draft: the synthesis draft, written first")
    text = fill(extract(pack.read_text(encoding="utf-8"), section),
                prompt_values(where, draft)) + "\n"
    guard_write(where.corpus)
    where.corpus.mkdir(parents=True, exist_ok=True)
    (where.corpus / f"dispatch-{section}.txt").write_text(text, encoding="utf-8")
    return text


def write_report(where: Layout, section: str, text: str) -> Path:
    """Write an agent's returned report under this sweep's run stamp; never replace one."""
    if section not in REPORTS:
        raise CorpusError(f"section {section} returns no report; reports are for "
                          f"{', '.join(REPORTS)}")
    manifest = read_manifest(where.corpus)
    if manifest is None:
        raise CorpusError(f"no manifest in {where.corpus}; build the corpus first")
    target = where.corpus / REPORTS[section]
    stamp = run_stamp(manifest)
    if _stamped(target, stamp):
        raise CorpusError(f"{target.name} already holds this sweep's report")
    guard_write(where.corpus)
    target.write_text(stamp + "\n" + text.rstrip("\n") + "\n", encoding="utf-8")
    return target


# --- the draft -----------------------------------------------------------------------------


def _draft_is_ours(stem: Path, seed: int, stamp: str) -> bool:
    markdown, record_path = stem.with_suffix(".md"), stem.with_suffix(".json")
    try:
        record = json.loads(record_path.read_text(encoding="utf-8"))
        record_seed, state = record["manifest"]["shuffle_seed"], record.get("state")
    except (OSError, ValueError, TypeError, KeyError, AttributeError):
        record_seed = state = None
    if state == "accepted":
        return False
    return _stamped(markdown, stamp) or record_seed == seed


def name(where: Layout, date: str) -> tuple[str | None, Path, Path]:
    """The draft's paths in the staging directory, never an earlier partition's.

    A draft this sweep left behind is continued under its own name. A name any earlier
    partition holds, in the staging directory or among the accepted ones, is suffixed.
    """
    if not re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", date):
        raise CorpusError(f"{date!r} is not a corpus date")
    manifest = read_manifest(where.corpus)
    if manifest is None:
        raise CorpusError(f"no manifest in {where.corpus}; build the corpus first")
    stamp, seed = run_stamp(manifest), manifest["shuffle_seed"]
    base, n, note = f"idea-partition-{date}", 2, None
    stem = base
    while True:
        staged, kept = where.staging / stem, where.partitions / stem
        taken = any(p.with_suffix(s).exists() for p in (staged, kept) for s in (".md", ".json"))
        if not taken:
            break
        if not any(kept.with_suffix(s).exists() for s in (".md", ".json")) \
                and _draft_is_ours(staged, seed, stamp):
            note = f"CONTINUE: {staged} is this sweep's own draft"
            break
        stem, n = f"{base}-{n}", n + 1
    staged = where.staging / stem
    return note, staged.with_suffix(".md"), staged.with_suffix(".json")


def _relative_to_checkout(path: Path) -> str:
    repository = _repository_of(path)
    resolved = path.resolve()
    if repository is None or not resolved.is_relative_to(repository):
        return resolved.as_posix()
    return resolved.relative_to(repository).as_posix()


def check_pair(markdown_path: Path, record_path: Path, corpus: Path,
               schema: Path = SCHEMA) -> list[str]:
    """Every way the draft and its record disagree with the schema, the corpus or each other."""
    record = json.loads(record_path.read_text(encoding="utf-8"))
    markdown = markdown_path.read_text(encoding="utf-8")
    validator = Draft7Validator(json.loads(schema.read_text(encoding="utf-8")))
    problems = [f"schema: {'/'.join(map(str, e.absolute_path)) or 'record'}: {e.message}"
                for e in validator.iter_errors(record)]
    if problems:
        return problems
    manifest = read_manifest(corpus)
    if manifest is None:
        return [f"no manifest in {corpus}"]
    corpus_ids = set(re.findall(r"^## (\d{6}) — ", (corpus / "corpus-R1.md")
                                .read_text(encoding="utf-8"), re.M))
    placed = [i for t in record["tracks"] for g in t["groups"] for i in g["ideas"]]
    placed += [u["id"] for u in record["unbatched"]]
    if not markdown.startswith(run_stamp(manifest)):
        problems.append("the markdown does not start with this sweep's run stamp")
    if record["manifest"] != {k: manifest[k] for k in ("corpus_size", "status", "shuffle_seed")}:
        problems.append("the record's manifest does not match the corpus manifest")
    if len(corpus_ids) != manifest["corpus_size"]:
        problems.append(f"corpus-R1.md lists {len(corpus_ids)} ids, the manifest says "
                        f"{manifest['corpus_size']}")
    problems += [f"in two places: {i}" for i in sorted({i for i in placed
                                                         if placed.count(i) > 1})]
    problems += [f"missing from the record: {i}" for i in sorted(corpus_ids - set(placed))]
    problems += [f"not in the corpus: {i}" for i in sorted(set(placed) - corpus_ids)]
    in_markdown = set(re.findall(r"\b(\d{6})\b", markdown)) & corpus_ids
    problems += [f"in the record, not the markdown: {i}"
                 for i in sorted(set(placed) - in_markdown)]
    problems += [f"in the markdown, not the record: {i}"
                 for i in sorted(in_markdown - set(placed))]
    tiers = record["decline_candidates"]
    nominated = [c["id"] for c in tiers["nominated_by_both"]]
    nominated += [c["id"] for c in tiers["nominated_by_one"]]
    problems += [f"decline candidate listed twice: {i}"
                 for i in sorted({i for i in nominated if nominated.count(i) > 1})]
    problems += [f"decline candidate not in a group or unbatched: {i}"
                 for i in sorted(set(nominated) - set(placed))]
    problems += [f"decline candidate not in the markdown: {i}"
                 for i in sorted(set(nominated) - in_markdown)]
    names = [t["name"] for t in record["tracks"]]
    names += [g["name"] for t in record["tracks"] for g in t["groups"]]
    problems += [f"name not in the markdown: {n!r}" for n in names if n not in markdown]
    expected = _relative_to_checkout(markdown_path)
    if record["markdown"] != expected:
        problems.append(f"the record names {record['markdown']}, not {expected}")
    return problems


def accept(where: Layout, markdown_path: Path, record_path: Path) -> tuple[Path, Path]:
    """Copy the accepted pair into the partitions directory, marked accepted.

    Run only on the owner's explicit acceptance. The copy's record names the copy's markdown.
    The staging draft is left as it is.
    """
    problems = check_pair(markdown_path, record_path, where.corpus)
    if problems:
        raise CorpusError("the draft does not pass its check:\n  " + "\n  ".join(problems))
    target_md = where.partitions / markdown_path.name
    target_json = where.partitions / record_path.name
    for target in (target_md, target_json):
        if target.exists():
            raise CorpusError(f"{target} already exists; an earlier partition is never replaced")
    where.partitions.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(markdown_path, target_md)
    record = json.loads(record_path.read_text(encoding="utf-8"))
    record["state"] = "accepted"
    record["markdown"] = _relative_to_checkout(target_md)
    target_json.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n",
                           encoding="utf-8")
    return target_md, target_json


# --- the command line ----------------------------------------------------------------------


def _parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    paths.add_arguments(common, PATH_KEYS)
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    def command(name: str, help_text: str) -> argparse.ArgumentParser:
        return sub.add_parser(name, help=help_text, parents=[common])

    command("locate", "print where the sweep's files live; exit 1 if the staging directory "
                      "is not gitignored")
    command("start", "resume a sweep in progress, or move an earlier sweep's files aside")
    built = command("build", "write the corpus files and manifest")
    built.add_argument("--status", default=DEFAULT_STATUS,
                       help="status or comma-separated statuses to select (default: triaged)")
    built.add_argument("--seed", type=int, help="the build's seed; drawn at random if omitted")
    built.add_argument("--out", type=Path,
                       help="output directory (default: <staging>/corpus in the primary checkout)")
    built.add_argument("--exclude", type=Path,
                       help="file of idea ids to leave out, one per line; none by default")
    built.add_argument("--stats", action="store_true", help="print the manifest; write nothing")
    prompted = command("prompt", "print one pack section, filled in, and save it as sent")
    prompted.add_argument("section", choices=SECTIONS)
    prompted.add_argument("--draft", type=Path, help="the synthesis draft (S and A2)")
    reported = command("report", "write an agent's returned report under the run stamp")
    reported.add_argument("section", choices=sorted(REPORTS))
    reported.add_argument("--file", type=Path, required=True, help="the returned text")
    named = command("name", "print the draft's markdown and record paths")
    named.add_argument("date", help="the corpus date, from locate")
    checked = command("check", "check the draft and its record against the corpus")
    checked.add_argument("markdown", type=Path)
    checked.add_argument("record", type=Path)
    accepted = command("accept", "copy the accepted pair into the partitions directory")
    accepted.add_argument("markdown", type=Path)
    accepted.add_argument("record", type=Path)
    return parser


def _locate(where: Layout) -> int:
    ignored = is_ignored(where.staging)
    print(f"primary: {where.primary}")
    print(f"staging: {where.staging}")
    print(f"corpus: {where.corpus}")
    print(f"partitions: {where.partitions}")
    print(f"primary_status: {status_digest(where.primary)}")
    manifest = read_manifest(where.corpus)
    if manifest is not None:
        print(f"corpus_size: {manifest['corpus_size']} | status: {','.join(manifest['status'])}"
              f" | seed: {manifest['shuffle_seed']} | corpus date: {corpus_date(where.corpus)}")
        print(f"stamp: {run_stamp(manifest)}")
    if not ignored:
        print(f"refused: {where.staging} is not gitignored in {where.primary}", file=sys.stderr)
        return 1
    print("staging ignored: yes")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    where = layout(paths.resolve(args))
    try:
        if args.command == "locate":
            return _locate(where)
        if args.command == "start":
            print("\n".join(start(where)))
        elif args.command == "build":
            facts = build(where.idea_log, args.out or where.corpus, parse_statuses(args.status),
                          args.exclude, args.seed, args.stats)
            if args.stats:
                print(json.dumps(facts, indent=2))
            else:
                print(f"corpus size: {facts['corpus_size']} (of {facts['selected']} selected)")
                print(f"excluded: {len(facts['excluded'])}")
                print(f"layered evidence (>1 finding): {len(facts['layered_evidence'])}")
                print(f"seed: {facts['shuffle_seed']}")
                print(f"written to {args.out or where.corpus}")
        elif args.command == "prompt":
            sys.stdout.write(prompt(where, args.section, args.draft))
        elif args.command == "report":
            print(f"wrote {write_report(where, args.section, args.file.read_text('utf-8'))}")
        elif args.command == "name":
            note, markdown, record = name(where, args.date)
            if note:
                print(note)
            print(markdown)
            print(record)
        elif args.command == "check":
            problems = check_pair(args.markdown, args.record, where.corpus)
            for problem in problems:
                print("FAIL", problem)
            print(f"{len(problems)} problem(s)")
            return 1 if problems else 0
        else:
            for path in accept(where, args.markdown, args.record):
                print(f"wrote {path}")
    except (CorpusError, IdeaError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
