#!/usr/bin/env python3
"""Assemble the idea-batching analyst corpora from the folded idea log.

Builds one corpus file per analyst for the idea-batching build (PROMPT-032), plus a
manifest recording what the analysts actually received. The corpus is the ideas
selected by `--status` (one status or a comma-separated list, default `triaged`)
minus every id the demo fast lane consumed, so it is smaller than the log and
changes whenever either moves — which is why the build session reads the manifest
rather than assuming a number.

Four analysts read the same ideas under two controlled variations, and the variations
live in the FILES rather than in the prompts, so no analyst can infer that its input
differs from anyone else's:

    corpus-R1.md   title, body, links, findings   id ascending
    corpus-R2.md   title, body, links, findings   id descending
    corpus-R3.md   title, body, links, findings   shuffled under the recorded seed
    corpus-R4.md   title, body, links             id ascending   <- the control

R4 is the bias control: nearly every triaged idea carries a finding written by one agent
charter, so a grouping R4 reproduces without findings is not inherited framing. Its file
is built by the same code path with findings withheld.

"Findings" means every annotation with kind == "finding", ANY author, in chronological
order. fold() returns annotations as a flat, unfiltered list mixing note, finding and
assessment kinds from several authors, so this filters by kind rather than trusting a
single-author assumption. Ideas carrying more than one finding are flagged in the corpus
as layered and possibly contradictory evidence; the set is computed, never hard-coded,
because the log is append-only and the set grows.

    uv run python tools/build_idea_corpus.py                    # build, random seed
    uv run python tools/build_idea_corpus.py --status open      # a different status slice
    uv run python tools/build_idea_corpus.py --seed 1234        # reproduce a run
    uv run python tools/build_idea_corpus.py --stats            # report only, write nothing
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.db.ideas import INVERSE_LINK_TYPE, fold, legal_transitions, load_events  # noqa: E402

OUT_DIR = ROOT / "_working" / "idea-corpus"
EXCLUSIONS = ROOT / "docs" / "00-working" / "demo-fast-lane-exclusions.yaml"

#: Dispositions that REMOVE an idea from the corpus. `dropped` deliberately does not
#: appear: an idea the fast lane considered and did not ship returns to the batching
#: corpus rather than falling between the two lanes (PROMPT-025 decision 14).
CONSUMING_DISPOSITIONS = frozenset({"queued", "fixed"})

#: Every disposition the exclusion file is allowed to carry. Anything outside this set is a
#: typo or a schema drift, and is warned about rather than silently treated as `dropped`.
KNOWN_DISPOSITIONS = CONSUMING_DISPOSITIONS | {"dropped"}

DEFAULT_STATUS = "triaged"


def valid_statuses() -> set[str]:
    """The idea record system's legal status values, read from the schema rather than restated.

    `legal_transitions()` already derives the `(from, to)` transition table out of
    `schemas/idea.schema.json`; the status filter's valid set is exactly the union of both
    sides of that table, so it needs no second, hard-coded list here.
    """
    transitions = legal_transitions()
    return {source for source, _ in transitions} | {target for _, target in transitions}

HEADER = """# Idea corpus — {analyst}

Generated by `uv run python tools/build_idea_corpus.py`. Do not edit by hand.

{count} ideas, presented in {order} order.{findings_note}

---
"""

#: Appended to the header ONLY for the finding-readers. The control's file must never
#: mention findings — not in an entry and not in the header — or it learns that its input
#: differs from someone else's, and a control that knows it is a control is not one.
LAYERED_NOTE = """ Each entry carries its title, body, links and findings.

Ideas marked **LAYERED EVIDENCE** carry more than one finding. Treat those as layered and
possibly internally contradictory accounts rather than a single settled one."""

PLAIN_NOTE = " Each entry carries its title, body and links."


def _display_path(path: Path) -> str:
    """Repository-relative where possible, absolute otherwise.

    An --exclusions path outside the repository is legitimate (a scratch file, an absolute
    path in a dispatch) and must not crash the build, which is what relative_to() does.
    """
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_exclusions(path: Path) -> tuple[set[str], set[str]]:
    """Return (ids removed from the corpus, ids recorded but returning to it).

    A missing file is an empty exclusion set, not an error: the demo fast lane and the
    batching pack are deliberately independent, and the pack must be runnable before the
    fast lane has finished.
    """
    if not path.exists():
        return set(), set()
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    consumed = data.get("consumed") or {}
    removed: set[str] = set()
    returned: set[str] = set()
    for key, value in consumed.items():
        disposition = (value or {}).get("disposition")
        if disposition in CONSUMING_DISPOSITIONS:
            removed.add(str(key))
            continue
        returned.add(str(key))
        if disposition not in KNOWN_DISPOSITIONS:
            # Warn rather than fail. The direction is safe — an unreadable disposition leaves
            # the idea IN the corpus, so nothing is silently dropped from the analysis — but a
            # typo ("QUEUED", a null, a missing key) would otherwise pass with no signal at all
            # and show up only as an unexpected corpus size. Raised by the GOV-008 stage 5 audit.
            print(
                f"build_idea_corpus: WARNING — {key} has unrecognized disposition "
                f"{disposition!r}; treating it as 'dropped' (kept in the corpus). "
                f"Known values: {', '.join(sorted(KNOWN_DISPOSITIONS))}.",
                file=sys.stderr,
            )
    return removed, returned


def findings_of(entry: dict[str, Any]) -> list[dict[str, Any]]:
    """Every annotation of kind 'finding', any author, chronologically."""
    found = [a for a in (entry.get("annotations") or []) if a.get("kind") == "finding"]
    return sorted(found, key=lambda a: str(a.get("at") or ""))


def build_corpus(
    statuses: frozenset[str],
    exclusions: Path = EXCLUSIONS,
) -> tuple[dict[str, dict[str, Any]], dict[str, Any]]:
    """Select the corpus and compute the facts the manifest reports.

    `statuses` is the caller's already-validated `--status` selection — one status or
    several, defaulting to `{"triaged"}`. The `"triaged"` key in the returned facts is kept
    under its historical name for `--stats` compatibility; it now counts every idea matching
    the selected status set, not only literally-`triaged` ones.
    """
    state = fold(load_events())
    triaged = {k: v for k, v in state.items() if v.get("status") in statuses}
    removed, returned = load_exclusions(exclusions)
    corpus = {k: v for k, v in triaged.items() if k not in removed}

    multi = sorted(k for k, v in corpus.items() if len(findings_of(v)) > 1)
    no_findings = sorted(k for k, v in corpus.items() if not findings_of(v))
    authors: dict[str, int] = {}
    for entry in corpus.values():
        for annotation in findings_of(entry):
            author = str(annotation.get("author"))
            authors[author] = authors.get(author, 0) + 1

    facts = {
        "ideas_in_log": len(state),
        "triaged": len(triaged),
        "excluded_by_fast_lane": sorted(removed & set(triaged)),
        "recorded_but_returned": sorted(returned & set(triaged)),
        "corpus_size": len(corpus),
        "layered_evidence": multi,
        "ideas_without_findings": no_findings,
        "finding_authors": dict(sorted(authors.items(), key=lambda kv: -kv[1])),
        "exclusions_file": _display_path(exclusions),
        "exclusions_file_present": exclusions.exists(),
    }
    return corpus, facts


def _inbound(corpus: dict[str, dict[str, Any]]) -> dict[str, list[tuple[str, str]]]:
    """Inbound edges per idea, so a dependency is visible from both ends."""
    inbound: dict[str, list[tuple[str, str]]] = {}
    for source, entry in corpus.items():
        for link in entry.get("links") or []:
            if link.get("retracted"):
                continue
            target = str(link.get("target"))
            edge = INVERSE_LINK_TYPE.get(link.get("type"), link.get("type"))
            inbound.setdefault(target, []).append((str(edge), source))
    return inbound


def render_idea(
    idea_id: str,
    entry: dict[str, Any],
    inbound: dict[str, list[tuple[str, str]]],
    *,
    include_findings: bool,
    layered: bool,
) -> str:
    """Render one idea. The control's file differs only in include_findings."""
    lines = [f"## {idea_id} — {entry.get('title', '')}"]
    if layered and include_findings:
        lines.append("")
        lines.append("**LAYERED EVIDENCE** — more than one finding.")
    lines.append("")
    lines.append(str(entry.get("body") or "").strip())

    outbound = [link for link in (entry.get("links") or []) if not link.get("retracted")]
    edges = [f"- {link.get('type')} -> {link.get('target')}" for link in outbound]
    edges += [f"- {edge} <- {source}" for edge, source in sorted(inbound.get(idea_id, []))]
    if edges:
        lines += ["", "### Links", ""] + edges

    if include_findings:
        found = findings_of(entry)
        if found:
            lines += ["", "### Findings", ""]
            for annotation in found:
                lines.append(f"*{annotation.get('author')}, {annotation.get('at')}*")
                lines.append("")
                lines.append(str(annotation.get("text") or "").strip())
                lines.append("")
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def render(
    corpus: dict[str, dict[str, Any]],
    order: list[str],
    *,
    analyst: str,
    order_name: str,
    include_findings: bool,
    layered: set[str],
) -> str:
    inbound = _inbound(corpus)
    head = HEADER.format(
        analyst=analyst,
        count=len(order),
        order=order_name,
        findings_note=LAYERED_NOTE if include_findings else PLAIN_NOTE,
    )
    body = "".join(
        render_idea(
            idea_id,
            corpus[idea_id],
            inbound,
            include_findings=include_findings,
            layered=idea_id in layered,
        )
        for idea_id in order
    )
    return head + "\n" + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--status",
        default=DEFAULT_STATUS,
        help="status or comma-separated statuses to select (default: triaged)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        help="shuffle seed for R3; a random one is drawn and recorded if omitted",
    )
    parser.add_argument(
        "--out", type=Path, default=OUT_DIR, help="output directory (default: _working/idea-corpus)"
    )
    parser.add_argument(
        "--exclusions",
        type=Path,
        default=EXCLUSIONS,
        help="fast-lane exclusion file; a missing file means an empty exclusion set",
    )
    parser.add_argument(
        "--stats", action="store_true", help="report the corpus facts and write nothing"
    )
    args = parser.parse_args(argv)

    requested = [s.strip() for s in args.status.split(",") if s.strip()]
    valid = valid_statuses()
    unknown = sorted(s for s in requested if s not in valid)
    if unknown:
        print(
            f"build_idea_corpus: unrecognized status {', '.join(unknown)} — "
            f"valid values are: {', '.join(sorted(valid))}",
            file=sys.stderr,
        )
        return 1
    statuses = frozenset(requested)

    corpus, facts = build_corpus(statuses, args.exclusions)
    if not corpus:
        print(
            f"build_idea_corpus: no ideas with status {sorted(statuses)} selected — "
            "nothing to build",
            file=sys.stderr,
        )
        return 1

    seed = args.seed if args.seed is not None else random.randrange(2**31)
    ascending = sorted(corpus)
    shuffled = list(ascending)
    random.Random(seed).shuffle(shuffled)
    layered = set(facts["layered_evidence"])

    plan = [
        ("R1", "corpus-R1.md", ascending, "id ascending", True),
        ("R2", "corpus-R2.md", list(reversed(ascending)), "id descending", True),
        ("R3", "corpus-R3.md", shuffled, f"shuffled (seed {seed})", True),
        ("R4", "corpus-R4.md", ascending, "id ascending", False),
    ]

    facts["shuffle_seed"] = seed
    facts["files"] = {analyst: name for analyst, name, _, _, _ in plan}

    if args.stats:
        print(json.dumps(facts, indent=2))
        return 0

    # Added only for the manifest, never for --stats: the `--stats` acceptance requirement is
    # byte-for-byte identical output for the default run, which this field would break.
    facts["status"] = sorted(statuses)

    args.out.mkdir(parents=True, exist_ok=True)
    for analyst, name, order, order_name, include_findings in plan:
        text = render(
            corpus,
            order,
            analyst=analyst,
            order_name=order_name,
            include_findings=include_findings,
            layered=layered,
        )
        (args.out / name).write_text(text, encoding="utf-8")

    (args.out / "manifest.json").write_text(
        json.dumps(facts, indent=2) + "\n", encoding="utf-8"
    )

    print(f"corpus size: {facts['corpus_size']} (of {facts['triaged']} triaged)")
    print(f"excluded by the fast lane: {len(facts['excluded_by_fast_lane'])}")
    print(f"layered evidence (>1 finding): {len(facts['layered_evidence'])}")
    print(f"shuffle seed: {seed}")
    print(f"written to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
