#!/usr/bin/env python3
"""Render host-specific workflow adapters from canonical agent workflow sources.

The manifest at `agent-workflows/workflows.yaml` names one Markdown source per workflow and declares
its authority, required capabilities, and generated targets. This tool validates that contract and
then writes deterministic Claude and Open Agent Skills adapters. Generated adapters are never edited
by hand.

    uv run python tools/generate_agent_workflows.py
    uv run python tools/generate_agent_workflows.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "agent-workflows" / "workflows.yaml"
# A "command" is agent-discoverable in Claude Code via the SlashCommand tool, not only by a person
# typing it, so an owner-only workflow must be refused there exactly as for a skill or agent.
AGENT_DISCOVERABLE_KINDS = {"skill", "agent", "command"}
AUTHORITIES = {"read-only", "agent-invocable", "owner-only"}
TARGET_PREFIXES = {
    ("claude", "skill"): Path(".claude/skills"),
    ("open-agent-skills", "skill"): Path(".agents/skills"),
    ("claude", "command"): Path(".claude/commands"),
    ("claude", "agent"): Path(".claude/agents"),
    ("codex", "agent"): Path(".codex/agents"),
}
GENERATED_NOTICE = "<!-- Generated by tools/generate_agent_workflows.py; do not edit. -->"
GENERATED_NOTICE_TOML = "# Generated by tools/generate_agent_workflows.py; do not edit."


class WorkflowError(ValueError):
    """The canonical workflow contract is invalid."""


def _render_markdown(
    frontmatter_lines: list[str], body: str, notice: str = GENERATED_NOTICE
) -> str:
    """Assemble a generated Markdown adapter from pre-rendered frontmatter lines and a body.

    Each caller decides its own field quoting so this stays byte-compatible with the exact styles
    already committed: a skill's `name:` is a plain scalar and its `description:` is JSON-quoted; a
    command's and a Claude agent's `description:`, `tools:`, `model:`, `effort:` are plain scalars
    matching the pre-generator hand-authored convention, while `argument-hint:` is JSON-quoted.
    """
    frontmatter = "---\n" + "".join(f"{line}\n" for line in frontmatter_lines) + "---\n\n"
    return frontmatter + notice + "\n\n" + body


def _render_agent(
    workflow_id: str, name: str, description: str, target: dict[str, Any], body: str
) -> str:
    render = _mapping(target.get("render"), f"{workflow_id}.render")
    return _render_markdown(
        [
            f"name: {name}",
            f"description: {description}",
            f"tools: {_required_render_str(render, 'tools', workflow_id)}",
            f"model: {_required_render_str(render, 'model', workflow_id)}",
            f"effort: {_required_render_str(render, 'effort', workflow_id)}",
            f"maxTurns: {_required_render_int(render, 'max_turns', workflow_id)}",
        ],
        body,
    )


def _required_render_str(render: dict[str, Any], key: str, workflow_id: str) -> str:
    value = render.get(key)
    if not isinstance(value, str) or not value:
        raise WorkflowError(f"{workflow_id}.render.{key} must be a nonempty string")
    return value


def _required_render_int(render: dict[str, Any], key: str, workflow_id: str) -> int:
    value = render.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise WorkflowError(f"{workflow_id}.render.{key} must be an integer")
    return value


def _render_codex_agent(
    workflow_id: str, name: str, description: str, target: dict[str, Any], body: str
) -> str:
    render = _mapping(target.get("render"), f"{workflow_id}.render")
    model = _required_render_str(render, "model", workflow_id)
    effort = _required_render_str(render, "model_reasoning_effort", workflow_id)
    sandbox = _required_render_str(render, "sandbox_mode", workflow_id)
    limits = _strings(
        render.get("unsupported_limits", []), f"{workflow_id}.render.unsupported_limits"
    )
    if not limits:
        raise WorkflowError(
            f"{workflow_id}: codex agent target must declare unsupported_limits explicitly — "
            "Codex has no per-agent turn or token budget control, and that omission must "
            "stay visible"
        )

    lines = [GENERATED_NOTICE_TOML, ""]
    lines.append(
        "# Execution limits this host cannot enforce (workflows.yaml render.unsupported_limits):"
    )
    for limit in limits:
        for wrapped in _wrap_comment(limit):
            lines.append(f"# {wrapped}")
    lines.append("")
    lines.append(f"name = {json.dumps(name, ensure_ascii=False)}")
    lines.append(f"description = {json.dumps(description, ensure_ascii=False)}")
    lines.append(f"model = {json.dumps(model, ensure_ascii=False)}")
    lines.append(f"model_reasoning_effort = {json.dumps(effort, ensure_ascii=False)}")
    lines.append(f"sandbox_mode = {json.dumps(sandbox, ensure_ascii=False)}")
    lines.append(f"developer_instructions = {json.dumps(body, ensure_ascii=False)}")
    return "\n".join(lines) + "\n"


def _wrap_comment(text: str, width: int = 96) -> list[str]:
    words = text.split()
    out: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            out.append(current)
            current = word
        else:
            current = candidate
    if current:
        out.append(current)
    return out or [text]


def _mapping(value: object, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise WorkflowError(f"{label} must be a mapping")
    return value


def _strings(value: object, label: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise WorkflowError(f"{label} must be a list of strings")
    if len(value) != len(set(value)):
        raise WorkflowError(f"{label} contains duplicates")
    return value


def _inside(root: Path, relative: str, label: str) -> Path:
    relative_path = Path(relative)
    if relative_path.is_absolute():
        raise WorkflowError(f"{label} must be repository-relative: {relative}")
    path = (root / relative_path).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise WorkflowError(f"{label} escapes the repository: {relative}") from error
    return path


def load_manifest(path: Path = MANIFEST) -> dict[str, Any]:
    """Load YAML without executing workflow content."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    manifest = _mapping(data, "manifest")
    if manifest.get("schema_version") != 1:
        raise WorkflowError("schema_version must be 1")
    if not isinstance(manifest.get("workflows"), list):
        raise WorkflowError("workflows must be a list")
    return manifest


def validate_and_render(manifest: dict[str, Any], root: Path = ROOT) -> dict[Path, str]:
    """Validate the manifest and return every target's deterministic bytes."""
    rendered: dict[Path, str] = {}
    workflow_ids: set[str] = set()

    for position, raw_workflow in enumerate(manifest["workflows"]):
        workflow = _mapping(raw_workflow, f"workflows[{position}]")
        workflow_id = workflow.get("id")
        name = workflow.get("name")
        description = workflow.get("description")
        authority = workflow.get("authority")
        source = workflow.get("source")
        string_fields = (workflow_id, name, description, source)
        if not all(isinstance(value, str) and value for value in string_fields):
            raise WorkflowError(f"workflows[{position}] has missing string fields")
        assert isinstance(workflow_id, str)
        assert isinstance(name, str)
        assert isinstance(description, str)
        assert isinstance(source, str)
        if workflow_id in workflow_ids:
            raise WorkflowError(f"duplicate workflow id: {workflow_id}")
        workflow_ids.add(workflow_id)
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise WorkflowError(f"{workflow_id}: invalid skill name {name!r}")
        if len(description) > 1024:
            raise WorkflowError(f"{workflow_id}: description exceeds 1024 characters")
        if authority not in AUTHORITIES:
            raise WorkflowError(f"{workflow_id}: unknown authority {authority!r}")

        required = set(_strings(workflow.get("requires"), f"{workflow_id}.requires"))
        source_path = _inside(root, source, f"{workflow_id}.source")
        canonical_root = (root / "agent-workflows").resolve()
        try:
            source_path.relative_to(canonical_root)
        except ValueError as error:
            raise WorkflowError(
                f"{workflow_id}: source is outside agent-workflows"
            ) from error
        if not source_path.is_file():
            raise WorkflowError(f"{workflow_id}: source does not exist: {source}")
        body = source_path.read_text(encoding="utf-8").strip() + "\n"

        targets = workflow.get("targets")
        if not isinstance(targets, list) or not targets:
            raise WorkflowError(f"{workflow_id}.targets must be a nonempty list")
        for target_position, raw_target in enumerate(targets):
            target = _mapping(raw_target, f"{workflow_id}.targets[{target_position}]")
            host = target.get("host")
            kind = target.get("kind")
            relative_path = target.get("path")
            if not all(isinstance(value, str) and value for value in (host, kind, relative_path)):
                raise WorkflowError(f"{workflow_id}: target has missing string fields")
            assert isinstance(host, str)
            assert isinstance(kind, str)
            assert isinstance(relative_path, str)
            prefix = TARGET_PREFIXES.get((host, kind))
            if prefix is None:
                raise WorkflowError(f"{workflow_id}: unsupported target {host}/{kind}")
            if authority == "owner-only" and kind in AGENT_DISCOVERABLE_KINDS:
                raise WorkflowError(
                    f"{workflow_id}: owner-only workflow cannot target agent-discoverable {kind}"
                )

            capabilities = _mapping(
                target.get("capabilities"), f"{workflow_id}.{host}.capabilities"
            )
            malformed = [
                key
                for key, value in capabilities.items()
                if not isinstance(key, str) or not isinstance(value, str) or not value
            ]
            if malformed:
                raise WorkflowError(
                    f"{workflow_id}/{host}: malformed capability mappings: {malformed}"
                )
            unsupported = set(
                _strings(target.get("unsupported"), f"{workflow_id}.{host}.unsupported")
            )
            mapped = set(capabilities)
            overlap = mapped & unsupported
            missing = required - mapped - unsupported
            unknown = (mapped | unsupported) - required
            if overlap:
                raise WorkflowError(
                    f"{workflow_id}/{host}: mapped and unsupported: {sorted(overlap)}"
                )
            if missing:
                raise WorkflowError(
                    f"{workflow_id}/{host}: undeclared capabilities: {sorted(missing)}"
                )
            if unknown:
                raise WorkflowError(
                    f"{workflow_id}/{host}: unknown capabilities: {sorted(unknown)}"
                )

            output_path = _inside(root, relative_path, f"{workflow_id}.{host}.path")
            target_root = (root / prefix).resolve()
            try:
                output_path.relative_to(target_root)
            except ValueError as error:
                raise WorkflowError(
                    f"{workflow_id}: target path is outside {prefix}"
                ) from error
            if output_path in rendered:
                raise WorkflowError(f"duplicate target path: {relative_path}")

            if kind == "agent" and host == "claude":
                rendered[output_path] = _render_agent(workflow_id, name, description, target, body)
            elif kind == "agent" and host == "codex":
                rendered[output_path] = _render_codex_agent(
                    workflow_id, name, description, target, body
                )
            elif kind == "command":
                lines = [f"description: {description}"]
                command_render = target.get("render")
                if command_render is not None:
                    command_render = _mapping(command_render, f"{workflow_id}.render")
                    if "argument_hint" in command_render:
                        hint = _required_render_str(command_render, "argument_hint", workflow_id)
                        lines.append(f"argument-hint: {json.dumps(hint, ensure_ascii=False)}")
                rendered[output_path] = _render_markdown(lines, body)
            elif kind == "skill":
                quoted_description = json.dumps(description, ensure_ascii=False)
                rendered[output_path] = _render_markdown(
                    [f"name: {name}", f"description: {quoted_description}"], body
                )
            else:
                raise WorkflowError(f"{workflow_id}: no renderer for {host}/{kind}")

    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if an adapter is missing or stale"
    )
    args = parser.parse_args(argv)

    try:
        outputs = validate_and_render(load_manifest(MANIFEST), ROOT)
    except (OSError, yaml.YAMLError, WorkflowError) as error:
        print(f"workflow manifest invalid: {error}", file=sys.stderr)
        return 2

    stale = [
        path
        for path, expected in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if args.check:
        if stale:
            print(
                "missing or stale workflow adapter(s): "
                + ", ".join(str(path.relative_to(ROOT)) for path in stale),
                file=sys.stderr,
            )
            return 1
        print(f"{len(outputs)} workflow adapter(s) current")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(outputs)} workflow adapter(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
