#!/usr/bin/env python3
"""Render a glossary from brain/'s `concept` memories.

Definitions are canonical in brain/ (PLAN-012); this renders them deterministically into a
generated Markdown document — never hand-written, same rule as docs/08-governance/catalog.md and
docs/00-working/ideas.md: a header says so, and a test fails on any difference from regenerated
output. Filterable by tag or system, so a targeted glossary ("everything about sys-brain") doesn't
require reading the whole knowledge base.

    uv run python tools/generate_glossary.py                     # write the full glossary
    uv run python tools/generate_glossary.py --tag frameworks    # a filtered glossary, to --out
    uv run python tools/generate_glossary.py --system sys-brain --out /tmp/g.md
    uv run python tools/generate_glossary.py --check             # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.db.source_validation import split_front_matter  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
BRAIN = ROOT / "brain"
TARGET = ROOT / "docs" / "08-governance" / "GLOSSARY.md"

HEADER = """# Glossary

Generated by `uv run python tools/generate_glossary.py` from `brain/`'s `concept` memories. Never
edit this file by hand — it is regenerated and a test fails on any difference. Definitions are
canonical in `brain/`; this is a rendered view of them.

To add or correct a term, edit its concept memory under `brain/concepts/`, then regenerate. A
filtered glossary — by tag or by system — can be generated on demand with `--tag`/`--system` and
`--out`; only this unfiltered glossary is committed.
"""


def load_concepts(brain: Path = BRAIN) -> list[dict[str, Any]]:
    """Every `type: concept` memory, in id order. A missing brain/ is an empty glossary."""
    entries: list[dict[str, Any]] = []
    if not brain.exists():
        return entries
    for path in sorted(brain.rglob("*.md")):
        if path.name == "index.md":
            continue
        split = split_front_matter(path.read_text(encoding="utf-8"))
        if split is None:
            continue
        meta = yaml.safe_load(split[0]) or {}
        if meta.get("type") != "concept":
            continue
        meta["content"] = split[1].strip()
        entries.append(meta)
    return sorted(entries, key=lambda entry: entry["id"])


def render(
    entries: list[dict[str, Any]], tag: str | None = None, system: str | None = None
) -> str:
    """The full glossary, or a slice of it filtered by tag and/or system."""
    filtered = [
        entry
        for entry in entries
        if (tag is None or tag in entry.get("tags", []))
        and (system is None or system in entry.get("systems", []))
    ]
    parts = [HEADER]
    if tag or system:
        scope = ", ".join(
            part
            for part in (f"tag={tag}" if tag else None, f"system={system}" if system else None)
            if part
        )
        parts.append(f"\n*Filtered by {scope}.*\n")
    for entry in filtered:
        parts.append(f"\n---\n\n## {entry['title']}\n\n{entry['content']}\n")
    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", help="Only terms carrying this tag")
    parser.add_argument("--system", help="Only terms carrying this system")
    parser.add_argument(
        "--out", type=Path, help="Write to a different path — required for a filtered glossary"
    )
    parser.add_argument("--check", action="store_true", help="Exit 1 if the target file is stale")
    args = parser.parse_args(argv)

    if (args.tag or args.system) and args.out is None and not args.check:
        print("error: a filtered glossary needs --out; only the unfiltered one is committed",
              file=sys.stderr)
        return 1

    entries = load_concepts()
    rendered = render(entries, tag=args.tag, system=args.system)
    target = args.out or TARGET

    if args.check:
        committed = target.read_text(encoding="utf-8") if target.exists() else ""
        if committed != rendered:
            print(
                f"error: {target.relative_to(ROOT) if target.is_relative_to(ROOT) else target} "
                "does not match regenerated output. Regenerate it; do not edit it by hand.",
                file=sys.stderr,
            )
            return 1
        print(f"{target} is current")
        return 0

    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {target} — {len(entries)} term(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
