#!/usr/bin/env python3
"""Render docs/00-working/ideas.md from _data/ideas.jsonl.

The markdown list was the source of truth until phase-idea-01; it is now a view. The
source is the event log, and this renders it — same rule as docs/08-governance/catalog.md
and the glossary in PLAN-012: a header saying so, and a test failing on any difference from
regenerated output.

Rendering is deterministic. Given the same log it produces the same bytes, which is what
lets the test treat a hand edit as a failure rather than a merge.

    uv run python tools/generate_ideas_md.py           # write the file
    uv run python tools/generate_ideas_md.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from append_idea import fold, load_events  # noqa: E402

from src.db.ideas import INVERSE_LINK_TYPE, link_diagnostics  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "00-working" / "ideas.md"
PRIORITY = ROOT / "docs" / "00-working" / "ideas-priority.yaml"

HEADER = """# Parked ideas

Generated by `uv run python tools/generate_ideas_md.py` from `_data/ideas.jsonl`. Never edit
this file by hand — it is regenerated and the test fails on any difference. To record an
idea or move one along, use the writer:

```bash
uv run python tools/append_idea.py add --file idea.md   # title = first line, body = the rest
uv run python tools/append_idea.py status 000007 reviewing
```

`--title "..." --body "..."` also exist, but only for a short, plain-text title typed by hand —
prose containing a backtick, `$(...)`, a quote or a newline is not safe as a quoted shell argument.

**Ideas are recorded as given.** They are not deduplicated, merged or judged at entry
([ADR-010](../04-decisions/ADR-010-idea-staging.md)). If an idea overlaps something that
already exists, note the overlap inside the entry — do not decline to record it. Triage is a
downstream process, not a gate at the door.

**The log is append-only and nothing in it is ever edited.** A status change appends an
event; it does not rewrite the entry. That is a fact about the storage now rather than a
rule someone has to keep, and it is why a discarded idea stays visible with its history —
the record of what was considered and rejected is worth as much as the record of what was
kept.

| Status | Meaning |
|---|---|
| `open` | Captured; nothing has looked at it |
| `triaged` | Scouting finished, findings attached; awaiting the owner |
| `reviewing` | The owner is actively considering it |
| `promoted` | Became a plan, requirement or phase — terminal, and names which |
| `discarded` | Rejected — terminal unless revisited, which is permitted once |
"""


def _inbound_links(state: dict[str, dict[str, object]]) -> dict[str, list[dict[str, object]]]:
    """Derived inverse edges, keyed by the idea each one points at — never stored (PLAN-017.04)."""
    inbound: dict[str, list[dict[str, object]]] = {idea: [] for idea in state}
    for idea, entry in state.items():
        for link in entry.get("links", []):  # type: ignore[union-attr]
            if link["retracted"]:
                continue
            target = link["target"]
            if target in inbound:
                inbound[target].append({"type": link["type"], "source": idea})
    return inbound


def _render_annotations(entry: dict[str, object]) -> str:
    """Notes and assessments stay visible; findings collapse so one triage run stays readable."""
    annotations = entry.get("annotations", [])
    if not annotations:  # type: ignore[arg-type]
        return ""
    visible = [a for a in annotations if a["kind"] != "finding"]  # type: ignore[index]
    findings = [a for a in annotations if a["kind"] == "finding"]  # type: ignore[index]
    parts = ["\n**Annotations**\n\n"]
    for a in visible:
        parts.append(f"- **{a['kind']}** by {a['author']} ({a['at']}): {a['text']}\n")
    if findings:
        parts.append(f"\n<details>\n<summary>{len(findings)} finding(s)</summary>\n\n")
        for a in findings:
            parts.append(f"- **finding** by {a['author']} ({a['at']}): {a['text']}\n")
        parts.append("\n</details>\n")
    return "".join(parts)


def _render_links(
    idea: str, entry: dict[str, object], inbound: dict[str, list[dict[str, object]]]
) -> str:
    outbound = [link for link in entry.get("links", []) if not link["retracted"]]  # type: ignore[index]
    incoming = inbound.get(idea, [])
    if not outbound and not incoming:
        return ""
    parts = ["\n**Links**\n\n"]
    for link in outbound:
        parts.append(f"- {link['type']} → `{link['target']}`\n")
    for edge in incoming:
        inverse = INVERSE_LINK_TYPE.get(edge["type"], edge["type"])
        parts.append(f"- {inverse} ← `{edge['source']}`\n")
    return "".join(parts)


def render(state: dict[str, dict[str, object]], next_up: list[str] | None = None) -> str:
    """The full file: priority queue first (if any), then every idea in identifier order."""
    parts = [HEADER]
    if next_up:
        parts.append("\n## Priority queue\n\n")
        parts.append(
            "Ideas that jump the queue, in order — see "
            "[ideas-priority.yaml](ideas-priority.yaml).\n\n"
        )
        for rank, idea in enumerate(next_up, start=1):
            title = state[idea]["title"] if idea in state else "unknown idea"
            parts.append(f"{rank}. `{idea}` — {title}\n")
    inbound = _inbound_links(state)
    for idea in sorted(state):
        entry = state[idea]
        stamp = f"**Created {entry['created']} · Status: `{entry['status']}`"
        if entry["revisits"]:
            stamp += f" · revisited {entry['revisits']}×"
        if entry["promoted_to"]:
            stamp += " · became " + ", ".join(entry["promoted_to"])  # type: ignore[arg-type]
        parts.append(f"\n---\n\n## {idea} · {entry['title']}\n\n{stamp}**\n\n{entry['body']}\n")
        parts.append(_render_annotations(entry))
        parts.append(_render_links(idea, entry, inbound))
    return "".join(parts)


def load_next_up() -> list[str]:
    if not PRIORITY.exists():
        return []
    data = yaml.safe_load(PRIORITY.read_text(encoding="utf-8")) or {}
    return list(data.get("next_up", []))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    state = fold(load_events())
    rendered = render(state, load_next_up())

    for idea, messages in sorted(link_diagnostics(state).items()):
        for message in messages:
            print(f"warning: {idea}: {message}", file=sys.stderr)

    if args.check:
        committed = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if committed != rendered:
            print(
                f"error: {TARGET.relative_to(ROOT)} does not match regenerated output. "
                "Regenerate it; do not edit it by hand.",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} — {len(state)} ideas")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
