#!/usr/bin/env python3
"""Render host-specific workflow adapters from canonical agent workflow sources.

The manifest at `agent-workflows/workflows.yaml` names one Markdown source per workflow and declares
its authority, required capabilities, and generated targets. This tool validates that contract and
then writes deterministic Claude and Open Agent Skills adapters. Generated adapters are never edited
by hand.

    uv run python tools/generate_agent_workflows.py
    uv run python tools/generate_agent_workflows.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "agent-workflows" / "workflows.yaml"
AGENT_DISCOVERABLE_KINDS = {"skill", "agent"}
AUTHORITIES = {"read-only", "agent-invocable", "owner-only"}
TARGET_PREFIXES = {
    ("claude", "skill"): Path(".claude/skills"),
    ("open-agent-skills", "skill"): Path(".agents/skills"),
}
GENERATED_NOTICE = "<!-- Generated by tools/generate_agent_workflows.py; do not edit. -->"


class WorkflowError(ValueError):
    """The canonical workflow contract is invalid."""


def _mapping(value: object, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise WorkflowError(f"{label} must be a mapping")
    return value


def _strings(value: object, label: str) -> list[str]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise WorkflowError(f"{label} must be a list of strings")
    if len(value) != len(set(value)):
        raise WorkflowError(f"{label} contains duplicates")
    return value


def _inside(root: Path, relative: str, label: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise WorkflowError(f"{label} escapes the repository: {relative}") from error
    return path


def load_manifest(path: Path = MANIFEST) -> dict[str, Any]:
    """Load YAML without executing workflow content."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    manifest = _mapping(data, "manifest")
    if manifest.get("schema_version") != 1:
        raise WorkflowError("schema_version must be 1")
    if not isinstance(manifest.get("workflows"), list):
        raise WorkflowError("workflows must be a list")
    return manifest


def validate_and_render(manifest: dict[str, Any], root: Path = ROOT) -> dict[Path, str]:
    """Validate the manifest and return every target's deterministic bytes."""
    rendered: dict[Path, str] = {}
    workflow_ids: set[str] = set()

    for position, raw_workflow in enumerate(manifest["workflows"]):
        workflow = _mapping(raw_workflow, f"workflows[{position}]")
        workflow_id = workflow.get("id")
        name = workflow.get("name")
        description = workflow.get("description")
        authority = workflow.get("authority")
        source = workflow.get("source")
        string_fields = (workflow_id, name, description, source)
        if not all(isinstance(value, str) and value for value in string_fields):
            raise WorkflowError(f"workflows[{position}] has missing string fields")
        assert isinstance(workflow_id, str)
        assert isinstance(name, str)
        assert isinstance(description, str)
        assert isinstance(source, str)
        if workflow_id in workflow_ids:
            raise WorkflowError(f"duplicate workflow id: {workflow_id}")
        workflow_ids.add(workflow_id)
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise WorkflowError(f"{workflow_id}: invalid skill name {name!r}")
        if len(description) > 1024:
            raise WorkflowError(f"{workflow_id}: description exceeds 1024 characters")
        if authority not in AUTHORITIES:
            raise WorkflowError(f"{workflow_id}: unknown authority {authority!r}")

        required = set(_strings(workflow.get("requires"), f"{workflow_id}.requires"))
        source_path = _inside(root, source, f"{workflow_id}.source")
        canonical_root = (root / "agent-workflows").resolve()
        try:
            source_path.relative_to(canonical_root)
        except ValueError as error:
            raise WorkflowError(
                f"{workflow_id}: source is outside agent-workflows"
            ) from error
        if not source_path.is_file():
            raise WorkflowError(f"{workflow_id}: source does not exist: {source}")
        body = source_path.read_text(encoding="utf-8").strip() + "\n"

        targets = workflow.get("targets")
        if not isinstance(targets, list) or not targets:
            raise WorkflowError(f"{workflow_id}.targets must be a nonempty list")
        for target_position, raw_target in enumerate(targets):
            target = _mapping(raw_target, f"{workflow_id}.targets[{target_position}]")
            host = target.get("host")
            kind = target.get("kind")
            relative_path = target.get("path")
            if not all(isinstance(value, str) and value for value in (host, kind, relative_path)):
                raise WorkflowError(f"{workflow_id}: target has missing string fields")
            assert isinstance(host, str)
            assert isinstance(kind, str)
            assert isinstance(relative_path, str)
            prefix = TARGET_PREFIXES.get((host, kind))
            if prefix is None:
                raise WorkflowError(f"{workflow_id}: unsupported target {host}/{kind}")
            if authority == "owner-only" and kind in AGENT_DISCOVERABLE_KINDS:
                raise WorkflowError(
                    f"{workflow_id}: owner-only workflow cannot target agent-discoverable {kind}"
                )

            capabilities = _mapping(
                target.get("capabilities"), f"{workflow_id}.{host}.capabilities"
            )
            unsupported = set(
                _strings(target.get("unsupported"), f"{workflow_id}.{host}.unsupported")
            )
            mapped = {
                key for key, value in capabilities.items() if isinstance(value, str) and value
            }
            overlap = mapped & unsupported
            missing = required - mapped - unsupported
            unknown = (mapped | unsupported) - required
            if overlap:
                raise WorkflowError(
                    f"{workflow_id}/{host}: mapped and unsupported: {sorted(overlap)}"
                )
            if missing:
                raise WorkflowError(
                    f"{workflow_id}/{host}: undeclared capabilities: {sorted(missing)}"
                )
            if unknown:
                raise WorkflowError(
                    f"{workflow_id}/{host}: unknown capabilities: {sorted(unknown)}"
                )

            output_path = _inside(root, relative_path, f"{workflow_id}.{host}.path")
            target_root = (root / prefix).resolve()
            try:
                output_path.relative_to(target_root)
            except ValueError as error:
                raise WorkflowError(
                    f"{workflow_id}: target path is outside {prefix}"
                ) from error
            if output_path in rendered:
                raise WorkflowError(f"duplicate target path: {relative_path}")
            frontmatter = (
                "---\n"
                f"name: {name}\n"
                f"description: {json.dumps(description, ensure_ascii=False)}\n"
                "---\n\n"
            )
            rendered[output_path] = frontmatter + GENERATED_NOTICE + "\n\n" + body

    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if an adapter is missing or stale"
    )
    args = parser.parse_args(argv)

    try:
        outputs = validate_and_render(load_manifest(MANIFEST), ROOT)
    except (OSError, yaml.YAMLError, WorkflowError) as error:
        print(f"workflow manifest invalid: {error}", file=sys.stderr)
        return 2

    stale = [
        path
        for path, expected in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if args.check:
        if stale:
            print(
                "missing or stale workflow adapter(s): "
                + ", ".join(str(path.relative_to(ROOT)) for path in stale),
                file=sys.stderr,
            )
            return 1
        print(f"{len(outputs)} workflow adapter(s) current")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(outputs)} workflow adapter(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
